enum
{
    RISCV_OP_LUI,
    RISCV_OP_AUIPC,

    RISCV_OP_JAL,
    RISCV_OP_JALR,

    RISCV_OP_BEQ,
    RISCV_OP_BNE,
    RISCV_OP_BLT,
    RISCV_OP_BGE,
    RISCV_OP_BLTU,
    RISCV_OP_BGEU,

    RISCV_OP_LB,
    RISCV_OP_LH,
    RISCV_OP_LW,
    RISCV_OP_LBU,
    RISCV_OP_LHU,

    RISCV_OP_SB,
    RISCV_OP_SH,
    RISCV_OP_SW,

    RISCV_OP_ADDI,
    RISCV_OP_SLTI,
    RISCV_OP_SLTIU,
    RISCV_OP_XORI,
    RISCV_OP_ORI,
    RISCV_OP_ANDI,

    RISCV_OP_SLLI,
    RISCV_OP_SRLI,
    RISCV_OP_SRAI,

    RISCV_OP_ADD,
    RISCV_OP_SUB,
    RISCV_OP_SLL,
    RISCV_OP_SLT,
    RISCV_OP_SLTU,
    RISCV_OP_XOR,
    RISCV_OP_SRL,
    RISCV_OP_SRA,
    RISCV_OP_OR,
    RISCV_OP_AND,

    RISCV_OP_FENCE,
    RISCV_OP_FENCE_I,

    RISCV_OP_ECALL,
    RISCV_OP_EBREAK,
    
    RISCV_OP_CSRRW,
    RISCV_OP_CSRRS,
    RISCV_OP_CSRRC,
    RISCV_OP_CSRRWI,
    RISCV_OP_CSRRSI,
    RISCV_OP_CSRRCI,

    RISCV_OP_MAX,        
};