/*
	Copyright (c) 1999-2008, Phillip Stanley-Marbell (author)
 
	All rights reserved.

	Redistribution and use in source and binary forms, with or without 
	modification, are permitted provided that the following conditions
	are met:

	*	Redistributions of source code must retain the above
		copyright notice, this list of conditions and the following
		disclaimer.

	*	Redistributions in binary form must reproduce the above
		copyright notice, this list of conditions and the following
		disclaimer in the documentation and/or other materials
		provided with the distribution.

	*	Neither the name of the author nor the names of its
		contributors may be used to endorse or promote products
		derived from this software without specific prior written 
		permission.

	THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
	"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
	LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
	FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE 
	COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
	INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
	BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
	LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER 
	CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
	LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN 
	ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
	POSSIBILITY OF SUCH DAMAGE.
*/

/*									*/
/*	Simulator specific additions to the SH arch (NIC, etc.)		*/
/*	Could probably have been done more cleanly by modeling them	*/
/*	as off-chip peripherals. We use the address range 0xE0000000	*/
/*	to 0xEFFFFFFF because it is unused/reserved on the SH7706.	*/
/*									*/

enum
{
	SUPERH_DEVSIM_TOP		= 0xEFFF0000,

	SUPERH_NIC_OUI_BYTES		= 0x10,
	SUPERH_NIC_DST_BYTES		= 0x10,
	SUPERH_NIC_REG_SPACING		= 0x00010000,

	SUPERH_NIC_NMR 			= SUPERH_DEVSIM_TOP,
	SUPERH_NIC_BRR 			= SUPERH_NIC_NMR - SUPERH_NIC_REG_SPACING,
	SUPERH_NIC_NCR 			= SUPERH_NIC_BRR - SUPERH_NIC_REG_SPACING,
	SUPERH_NIC_TDR 			= SUPERH_NIC_NCR - SUPERH_NIC_REG_SPACING,
	SUPERH_NIC_NSR 			= SUPERH_NIC_TDR - SUPERH_NIC_REG_SPACING,
	SUPERH_NIC_RDR 			= SUPERH_NIC_NSR - SUPERH_NIC_REG_SPACING,
	SUPERH_NIC_MAXFSZ		= SUPERH_NIC_RDR - SUPERH_NIC_REG_SPACING,
	SUPERH_NIC_RXFSZ		= SUPERH_NIC_MAXFSZ - SUPERH_NIC_REG_SPACING,
	SUPERH_NIC_OUI 			= SUPERH_NIC_RXFSZ - SUPERH_NIC_REG_SPACING,
	SUPERH_NIC_DST 			= SUPERH_NIC_OUI - SUPERH_NIC_REG_SPACING,
	SUPERH_NIC_NCSENSE 		= SUPERH_NIC_DST - SUPERH_NIC_REG_SPACING,
	SUPERH_NIC_NCOLLS 		= SUPERH_NIC_NCSENSE - SUPERH_NIC_REG_SPACING,
	SUPERH_NIC_CSENSE 		= SUPERH_NIC_NCOLLS - SUPERH_NIC_REG_SPACING,

	SUPERH_DEVLOGPRINT		= SUPERH_NIC_CSENSE - 1,

	SUPERH_USECS_END		= SUPERH_DEVLOGPRINT,
	SUPERH_USECS_BEGIN		= SUPERH_DEVLOGPRINT - 4,

	SUPERH_SIMCMD_CTL		= SUPERH_USECS_BEGIN - 1,
	SUPERH_SIMCMD_DATA		= SUPERH_SIMCMD_CTL - 1,

	SUPERH_RAND_END			= SUPERH_SIMCMD_DATA,
	SUPERH_RAND_BEGIN		= SUPERH_SIMCMD_DATA - 4,

	// TODO: remove orbit and velocity, and update the sys/kern/superH/sh7708.h
	SUPERH_ORBIT_END 		= SUPERH_RAND_BEGIN,
	SUPERH_ORBIT_BEGIN 		= SUPERH_RAND_BEGIN - 4,
	SUPERH_VELOCITY_END 		= SUPERH_ORBIT_BEGIN,
	SUPERH_VELOCITY_BEGIN 		= SUPERH_ORBIT_BEGIN - 8,

	SUPERH_XLOC_END 		= SUPERH_VELOCITY_BEGIN,
	SUPERH_XLOC_BEGIN 		= SUPERH_VELOCITY_BEGIN - 8,
	SUPERH_YLOC_END 		= SUPERH_XLOC_BEGIN,
	SUPERH_YLOC_BEGIN 		= SUPERH_XLOC_BEGIN - 8,
	SUPERH_ZLOC_END 		= SUPERH_YLOC_BEGIN,
	SUPERH_ZLOC_BEGIN 		= SUPERH_YLOC_BEGIN - 8,

	SUPERH_SENSOR_REG_SPACING 	= 0x00010000,
	SUPERH_SENSREAD_END		= SUPERH_ZLOC_BEGIN,
	SUPERH_SENSREAD_BEGIN		= SUPERH_ZLOC_BEGIN - SUPERH_SENSOR_REG_SPACING,
	SUPERH_SENSWRITE_END		= SUPERH_SENSREAD_BEGIN,
	SUPERH_SENSWRITE_BEGIN		= SUPERH_SENSREAD_BEGIN - SUPERH_SENSOR_REG_SPACING,

	SUPERH_THREADID			= SUPERH_SENSWRITE_BEGIN - 4,

	SUPERH_NUMAREGION_REG_SPACING 	= 0x00010000,
	SUPERH_NUMAREGION_RDCNT_END	= SUPERH_THREADID,
	SUPERH_NUMAREGION_RDCNT_BEGIN	= SUPERH_THREADID - SUPERH_NUMAREGION_REG_SPACING,

	SUPERH_NUMAREGION_WRCNT_END	= SUPERH_NUMAREGION_RDCNT_BEGIN,
	SUPERH_NUMAREGION_WRCNT_BEGIN	= SUPERH_NUMAREGION_RDCNT_BEGIN - SUPERH_NUMAREGION_REG_SPACING,

	SUPERH_NUMAREGION_COUNT		= SUPERH_NUMAREGION_WRCNT_BEGIN - 4,

	SUPERH_BATTPERCENT		= SUPERH_NUMAREGION_COUNT - 4,

	SUPERH_LOGMARK_END		= SUPERH_BATTPERCENT,
	SUPERH_LOGMARK_BEGIN		= SUPERH_BATTPERCENT - 32,

	SUPERH_NETTRACEMARK_END		= SUPERH_LOGMARK_BEGIN,
	SUPERH_NETTRACEMARK_BEGIN	= SUPERH_LOGMARK_BEGIN - 32,

	SUPERH_DEVSIM_BOTTOM		= SUPERH_BATTPERCENT,
};
