#!/bin/sh

	if [ $# -ne 0 ]; then
		echo 1>&2 Usage: $0
		exit 127
	fi


	echo '/*	This is dependent on latencies-riscv.h	*/'
	echo 'enum'
	echo '{'
	cat latencies-riscv.h | grep _OP_ | sed "s/.*\[\(R.*_OP_.*[A-Z0-9]\)\].*/\t\1,/" | sed "s/^\(.*MAX,\)/\n\1\n/"
	echo '};'
