#!/bin/sh

	if [ $# -ne 1 ]; then
		echo 1>&2 Usage: $0 '<path to a Gnu awk>'
		exit 127
	fi


	echo '/*	This is dependent on latencies-hitachi-sh.h	*/'
	echo 'enum'
	echo '{'
	cat latencies-hitachi-sh.h | grep _OP_ | sed "s/.*\[\(SUPERH_OP_.*[A-Z0-9]\)\].*/\1,/" | sed "s/^\(.*MAX,\)/MAX~\1/" | $1 -F'~' '{if($1=="MAX"){print "\n\t"$2"\n"}else{print "\t"$1}}'
	echo '};'
