#!/bin/sh

	if [ $# -ne 1 ]; then
		echo 1>&2 Usage: $0 '<path to a gnu sed>'
		exit 127
	fi


	echo '/*	This is dependent on latencies-hitachi-sh.h	*/'
	echo 'enum'
	echo '{'
	cat latencies-hitachi-sh.h | grep _OP_ | $1 "s/.*\[\(SUPERH_OP_.*[A-Z0-9]\)\].*/\t\1,/" | $1 "s/^\(.*MAX,\)/\n\1\n/"
	echo '};'
