#!/bin/sh

	if [ $# -ne 1 ]; then
		echo 1>&2 Usage: $0 "<path to Gnu awk>" 
		exit 127
	fi


	echo 'Help Helpstrs[] =\'
	echo '{\'
	cat lex-hitachi-sh.c | grep '/\*+' | sort | $1 -F'*|_|}|{|+|,|:' '{print "\t{\n\t\t\t" $2 ",\n\t\t\t\"\tDescription:" $8 "\",\n\t\t\t\"\tArguments:\t" $9 "\",\n\t},"}'
	echo '};'
	echo 'int	nHelpstrs ='`cat lex-hitachi-sh.c | grep '/\*+' | wc -l`';'
	echo 'int	uniqHelpstrs ='`cat lex-hitachi-sh.c | grep '/\*+' | sort -t '"' -k 2 | $1 '{print $2}' | sort | uniq | wc -l`';'
