#!/bin/sh


	if [ $# -ne 1 ]; then
		echo 1>&2 Usage: $0 "<path to Gnu awk>" 
		exit 127
	fi


	echo '\section{Simulator Command Set}'
	cat lex.c | grep '/\*+' | sort -t ',' | sed 's/none//' | $1 -F'*|_|}|{|+|,|:|"'\
		'{print "\n\\subsection{\\bf " $3 "}\\inxx{{\\tt "$3"}}\n\\label{manpage:"$3"}\n{\\bf Description}: " $10\
		"\\\\[1.5ex]\n{\\em Synopsis}:\n\\scriptsize\n\\begin{verbatim}\n"\
	"   " $3 "   " $11\
		"\n\\end{verbatim}\n\\normalsize\n"}'

