#!/bin/sh


	if [ $# -ne 1 ]; then
		echo 1>&2 Usage: $0 "<path to Gnu awk>" 
		exit 127
	fi


	echo 'char *riscv_opstrs[] =\'
	echo '{'
	cat decode-riscv.h | sed "s/_OP_/~OP~/g" | grep OP | sed "s/.*RISCV~/RISCV~/g" | sed "s/.*RV32F~/RV32F~/g" | sed "s/.*RV32D~/RV32D~/g" | $1 -F',|~' '{print "\t["$1"_"$2"_"$3"] \t\t\""$3"\","}'
	echo '};'
