#!/bin/sh


	if [ $# -ne 1 ]; then
		echo 1>&2 Usage: $0 "<path to Gnu awk>" 
		exit 127
	fi


	echo 'char *opstrs[] =\'
	echo '{'
	cat decode-hitachi-sh.h | grep OP | $1 -F',|_' '{print "\t\t\""$2"\","}'
	echo '};'
