#!/bin/sh


	if [ $# -ne 1 ]; then
		echo 1>&2 Usage: $0 "<path to Gnu awk>" 
		exit 127
	fi


	echo 'char *riscv_opstrs[] =\'
	echo '{'
	cat decode-riscv.h | grep OP | sed "s/.*RISCV_/RISCV_/g" | sed "s/.*RV32F_/RV32F_/g" | gawk -F',|_' '{print "\t["$1"_"$2"_"$3"] \t\t\""$3"\","}'
	echo '};'
