#!/bin/sh


	if [ $# -ne 1 ]; then
		echo 1>&2 Usage: $0 "<path to Gnu awk>" 
		exit 127
	fi


	echo 'char *msp430_opstrs[] =\'
	echo '{'
	cat decode-ti-msp430.h | grep OP | $1 -F',|_' '{print "\t[OP_"$2"] \t\t\""$2"\","}'
	echo '};'
