#!/bin/sh


	if [ $# -ne 1 ]; then
		echo 1>&2 Usage: $0 "<path to Gnu awk>" 
		exit 127
	fi


	echo 'char *superH_opstrs[] =\'
	echo '{'
	cat decode-hitachi-sh.h | grep SUPERH_OP | $1 -F',|_' '{print "\t[SUPERH_OP_"$3"]\t\t\""$3"\","}'
	echo '};'
