#!/bin/sh


	if [ $# -ne 1 ]; then
		echo 1>&2 Usage: $0 "<path to Gnu awk>" 
		exit 127
	fi


	echo 'char *msp430_opstrs[] =\'
	echo '{'
	cat decode-ti-msp430.h | grep MSP430_OP | $1 -F',|_' '{print "\t[MSP430_OP_"$3"]\t\t\""$3"\","}'
	echo '};'
