char *riscv_opstrs[] =\
{
	[RISCV_OP_LUI] 		"LUI",
	[RISCV_OP_AUIPC] 		"AUIPC",
	[RISCV_OP_JAL] 		"JAL",
	[RISCV_OP_JALR] 		"JALR",
	[RISCV_OP_BEQ] 		"BEQ",
	[RISCV_OP_BNE] 		"BNE",
	[RISCV_OP_BLT] 		"BLT",
	[RISCV_OP_BGE] 		"BGE",
	[RISCV_OP_BLTU] 		"BLTU",
	[RISCV_OP_BGEU] 		"BGEU",
	[RISCV_OP_LB] 		"LB",
	[RISCV_OP_LH] 		"LH",
	[RISCV_OP_LW] 		"LW",
	[RISCV_OP_LBU] 		"LBU",
	[RISCV_OP_LHU] 		"LHU",
	[RISCV_OP_SB] 		"SB",
	[RISCV_OP_SH] 		"SH",
	[RISCV_OP_SW] 		"SW",
	[RISCV_OP_ADDI] 		"ADDI",
	[RISCV_OP_SLTI] 		"SLTI",
	[RISCV_OP_SLTIU] 		"SLTIU",
	[RISCV_OP_XORI] 		"XORI",
	[RISCV_OP_ORI] 		"ORI",
	[RISCV_OP_ANDI] 		"ANDI",
	[RISCV_OP_SLLI] 		"SLLI",
	[RISCV_OP_SRLI] 		"SRLI",
	[RISCV_OP_SRAI] 		"SRAI",
	[RISCV_OP_ADD] 		"ADD",
	[RISCV_OP_SUB] 		"SUB",
	[RISCV_OP_SLL] 		"SLL",
	[RISCV_OP_SLT] 		"SLT",
	[RISCV_OP_SLTU] 		"SLTU",
	[RISCV_OP_XOR] 		"XOR",
	[RISCV_OP_SRL] 		"SRL",
	[RISCV_OP_SRA] 		"SRA",
	[RISCV_OP_OR] 		"OR",
	[RISCV_OP_AND] 		"AND",
	[RISCV_OP_FENCE] 		"FENCE",
	[RISCV_OP_FENCE] 		"FENCE",
	[RISCV_OP_ECALL] 		"ECALL",
	[RISCV_OP_EBREAK] 		"EBREAK",
	[RISCV_OP_CSRRW] 		"CSRRW",
	[RISCV_OP_CSRRS] 		"CSRRS",
	[RISCV_OP_CSRRC] 		"CSRRC",
	[RISCV_OP_CSRRWI] 		"CSRRWI",
	[RISCV_OP_CSRRSI] 		"CSRRSI",
	[RISCV_OP_CSRRCI] 		"CSRRCI",
	[RISCV_OP_MAX] 		"MAX",
	
	/* RV32F */
	[RV32F_OP_FLW]		"FLW",
	[RV32F_OP_FSW]		"FSW",

	[RV32F_OP_FMADD_S]		"FMADD_S",
	[RV32F_OP_FMSUB_S]		"FMSUB_S",
	[RV32F_OP_FNMSUB_S]		"FNMSUB_S",
	[RV32F_OP_FNMADD_S]		"FNMADD_S",

	[RV32F_OP_FADD_S]		"FADD_S",
	[RV32F_OP_FSUB_S]		"FSUB_S",
	[RV32F_OP_FMUL_S]		"FMUL_S",
	[RV32F_OP_FDIV_S]		"FDIV_S",
	[RV32F_OP_FSQRT_S]		"FSQRT_S",

	[RV32F_OP_FSGNJ_S]		"FSGNJ_S",
	[RV32F_OP_FSGNJN_S]		"FSGNJN_S",
	[RV32F_OP_FSGNJX_S]		"FSGNJX_S",

	[RV32F_OP_FMIN_S]		"FMIN_S",
	[RV32F_OP_FMAX_S]		"FMAX_S",

	[RV32F_OP_FCVT_W_S]		"FCVT_W_S",
	[RV32F_OP_FCVT_WU_S]		"FCVT_WU_S",

	[RV32F_OP_FMV_X_W]		"FMV_X_W",

	[RV32F_OP_FEQ_S]		"FEQ_S",
	[RV32F_OP_FLT_S]		"FLT_S",
	[RV32F_OP_FLE_S]		"FLE_S",

	[RV32F_OP_FCLASS_S]		"FCLASS_S",

	[RV32F_OP_FCVT_S_W]		"FCVT_S_W",
	[RV32F_OP_FCVT_S_WU]		"FCVT_S_WU",

	[RV32F_OP_FMV_W_X]		"FMV_W_X",

	[RV32F_OP_FMAX]		"FMAX"

};
